# Generated by Django 3.2.7 on 2021-09-13 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('users', '0002_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='tasks.task'),
        ),
    ]
