# Generated by Django 3.2.7 on 2021-09-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_task', models.CharField(default='', max_length=2000)),
                ('task_status', models.IntegerField(choices=[(0, 'Not Completed'), (1, 'Completed')], default=0, verbose_name='task status')),
            ],
        ),
    ]
