# Generated by Django 3.2.7 on 2021-09-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned_task',
            new_name='task_description',
        ),
        migrations.AddField(
            model_name='task',
            name='task_title',
            field=models.CharField(default='', max_length=70),
        ),
    ]
